export const STORE_PLACEHOLDER_URL = "#coming-soon";
export const SITE_URL = "https://meetings.ro";
export const OG_IMAGE_URL = `${SITE_URL}/assets/branding/og-image.png`;
export const BRAND_LOGO_PATH = "/assets/branding/meetings-logo.svg";

export const landingContent = {
  ro: {
    locale: "ro_RO",
    meta: {
      title: "Meetings.ro — Înregistrare și Transcriere AI",
      description:
        "Înregistrare și transcriere AI pentru ședințe, interviuri și rapoarte structurate. Creat pentru Banking, Legal, Jurnalism și administrație publică.",
      keywords: [
        "inregistrare AI",
        "transcriere AI",
        "raport structurat automat",
        "software primarie",
        "minute sedinta",
        "banking meeting reports",
        "legal transcription",
      ],
    },
    navigation: {
      features: "Funcționalități",
      structure: "Cele 9 câmpuri",
      pricing: "Prețuri",
      security: "Confidențialitate",
      faq: "Întrebări",
      download: "Descarcă",
      openMenu: "Deschide meniul",
    },
    store: {
      tooltip: "Disponibil în curând",
      label: "Descarcă din store",
      altAppStore: "Descarcă Meetings.ro din App Store",
      altPlayStore: "Descarcă Meetings.ro din Google Play",
    },
    hero: {
      eyebrow: "Transcriere AI pentru echipe și organizații",
      title: "Orice ședință. Raport în minute.",
      lead:
        "Transcriere AI + rapoarte structurate pentru Banking, Legal, Jurnalism și administrație publică. Totul într-un flux simplu, clar și ușor de verificat.",
      secondaryCta: "Vezi cum arată raportul",
      trustLine: "Dacă știi să folosești WhatsApp, știi să folosești Meetings.",
      proofs: [
        { value: "~2 min", label: "pentru un raport gata de arhivare" },
        { value: "Offline", label: "înregistrezi pe teren și încarci ulterior" },
        { value: "RO", label: "suport și onboarding în limba română" },
      ],
    },
    problem: {
      eyebrow: "Realitatea din teren",
      title: "Știm că internetul nu este mereu de partea ta.",
      lead:
        "Întâlnirile din teren, localități mici sau organizații distribuite nu se țin mereu cu semnal bun sau la birou. Meetings este gândit exact pentru acest ritm de lucru.",
      body:
        "Înregistrezi ședința pe orice telefon sau reportofon. Te întorci la birou. Încarci fișierul. Primești raportul structurat, clar și pregătit pentru verificare internă.",
      calloutTitle: "Upload offline",
      calloutBody:
        "Înregistrezi oriunde, chiar și fără semnal. Încarci fișierul când revii la birou și continui procesarea fără bătăi de cap.",
      calloutBadge: "Funcționează și cu conexiuni slabe",
      steps: [
        "1. Înregistrezi ședința pe telefon, laptop sau reportofon.",
        "2. Încarci audio când ai din nou acces la internet.",
        "3. Primești un document structurat, nu doar text brut.",
      ],
    },
    fields: {
      eyebrow: "Document structurat, nu simplă transcriere",
      title: "Cele 9 câmpuri automate care fac raportul audit-ready.",
      lead:
        "Meetings nu livrează pagini de text greu de urmărit. Livrează informația exact în formatul de care organizația ta are nevoie pentru verificare și arhivare.",
      statement: "Nu este doar transcriere. Este un document clar, structurat și pregătit pentru cerințe oficiale.",
      items: [
        { label: "Data și ora", description: "Localizezi imediat ședința și contextul administrativ." },
        { label: "Localitate / UAT", description: "Arhivezi corect pe comună, sat sau localitate." },
        { label: "Participanți", description: "Ai lista actorilor relevanți pentru raportare." },
        { label: "Ordinea de zi", description: "Vezi rapid subiectele discutate, în ordinea corectă." },
        { label: "Obiective", description: "Separi clar scopul întâlnirii de restul conversației." },
        { label: "Discuții (sinteză)", description: "Primești ideile importante, nu zgomotul din conversație." },
        { label: "Decizii", description: "Extragi hotărârile fără să recitești tot audio-ul." },
        { label: "Concluzii", description: "Închizi întâlnirea cu o sinteză clară și ușor de verificat." },
        { label: "Pași următori", description: "Rămân vizibile responsabilitățile și acțiunile de follow-up." },
      ],
    },
    verticals: {
      eyebrow: "Adaptat pentru domeniul tău",
      title: "Același flux, adaptat pentru fiecare verticală importantă.",
      lead:
        "Meetings.ro extrage informația relevantă în funcție de contextul tău, fără să schimbe modul simplu de lucru.",
      cards: [
        {
          title: "GAL / Administrativ",
          isNew: false,
          extracts: ["Cele 9 câmpuri oficiale", "Localitate", "Participanți"],
          useCase: "Rapoarte LEADER generate automat",
          testid: "industry-admin-card",
        },
        {
          title: "Banking & Financiar",
          isNew: true,
          extracts: ["Compliance points", "Action items", "Risk flags"],
          useCase: "Minute de ședință conforme BNR",
          testid: "industry-banking-card",
        },
        {
          title: "Legal & Juridic",
          isNew: true,
          extracts: ["Clauze discutate", "Termene", "Obligații"],
          useCase: "Documente negociere structurate instant",
          testid: "industry-legal-card",
        },
        {
          title: "Jurnalism & Media",
          isNew: true,
          extracts: ["Quote-uri cheie", "Persoane citate", "Unghi editorial"],
          useCase: "Interviuri transcrise și indexate",
          testid: "industry-media-card",
        },
      ],
      newBadge: "Nou",
    },
    features: {
      eyebrow: "Funcții făcute pentru birocrația reală",
      title: "Tot ce îți trebuie ca să găsești, exporți și recuperezi rapid orice ședință.",
      lead:
        "Pe lângă raportul generat, Meetings organizează și păstrează munca într-un mod ușor de folosit pentru echipe administrative.",
      cards: [
        {
          title: "Arhivă pe localități",
          description: "Dosarele se organizează automat pe localități precum Chilia Veche, Crișan sau Maliuc.",
          detail: "Mai puțin timp pierdut căutând fișiere vechi.",
          testid: "feature-archive-card",
        },
        {
          title: "Export instant",
          description: "Descarci imediat raportul în PDF sau Word (DOCX) pentru tipărire și arhivare.",
          detail: "Fără rescriere manuală înainte de trimitere.",
          testid: "feature-export-card",
        },
        {
          title: "Căutare rapidă",
          description: "Găsești orice ședință după dată sau localitate în câteva secunde.",
          detail: "Important când verifici documente din anii trecuți.",
          testid: "feature-search-card",
        },
      ],
    },
    security: {
      eyebrow: "Încredere și confidențialitate",
      title: "Date tratate cu seriozitatea pe care o cere administrația publică.",
      lead:
        "Pentru instituții publice, viteza contează doar dacă vine la pachet cu confidențialitate, claritate și suport local.",
      bullets: [
        "GDPR și confidențialitate în fluxul de procesare",
        "Fără soluții publice nesigure pentru documente sensibile",
        "Suport tehnic în limba română",
        "Produs creat pentru fluxuri administrative locale",
      ],
      badges: ["GDPR focus", "Suport în română", "Public sector fit"],
      cardTitle: "Construit în România, pentru instituții din România",
      cardLead:
        "Înțelegem termenii, ritmul și presiunea din administrația locală. De aceea produsul pune accent pe claritate, viteză și arhivare corectă.",
      cardItems: [
        "Procesare dedicată instituțiilor",
        "Interfață simplă pentru utilizatori non-tehnici",
        "Documente ușor de verificat și exportat",
      ],
    },
    pricing: {
      eyebrow: "Pricing nou, în EUR",
      title: "Alegi planul potrivit pentru ritmul real al echipei tale.",
      lead:
        "Am înlocuit complet vechiul pricing cu planuri în EUR, ore clare și verticale incluse în funcție de etapă.",
      toggleMonthly: "Lunar",
      toggleAnnual: "Anual",
      savingsLabel: "Economisești 2 luni cu plata anuală",
      vatNote: "Prețuri fără TVA",
      plans: [
        {
          name: "Free",
          badge: "Start",
          monthlyPrice: "0€",
          annualPrice: "0€",
          monthlyPeriod: "/lună",
          annualPeriod: "/an",
          detail: "10h înregistrare / lună",
          features: ["Model AI: Nano", "1 vertical inclus", "Export PDF basic", "Stocare 1GB"],
          ctaLabel: "În curând",
          ctaType: "coming-soon",
          highlight: false,
          badgeTone: "neutral",
          testid: "pricing-free-card",
        },
        {
          name: "Pro",
          badge: "Upgrade",
          monthlyPrice: "20€",
          annualPrice: "200€",
          monthlyPeriod: "/lună",
          annualPeriod: "/an",
          detail: "30h înregistrare / lună",
          features: ["Model AI: Mini", "1 vertical inclus", "Export PDF + DOCX", "Stocare 10GB"],
          ctaLabel: "În curând",
          ctaType: "coming-soon",
          highlight: false,
          badgeTone: "neutral",
          testid: "pricing-pro-card",
        },
        {
          name: "Business",
          badge: "Popular",
          monthlyPrice: "60€",
          annualPrice: "600€",
          monthlyPeriod: "/lună",
          annualPeriod: "/an",
          detail: "60h înregistrare / lună",
          features: ["Model AI: Pro", "3 verticale incluse", "Export PDF + DOCX branded", "Stocare 50GB", "Semantic search"],
          ctaLabel: "Alege Business",
          ctaType: "store-badges",
          highlight: true,
          badgeTone: "featured",
          testid: "pricing-business-card",
        },
        {
          name: "Enterprise",
          badge: "Enterprise",
          monthlyPrice: "900€",
          annualPrice: "900€",
          monthlyPeriod: "/an",
          annualPeriod: "/an",
          detail: "Ore nelimitate",
          features: ["Model AI: Pro", "Verticale nelimitate", "SLA 99.9%", "Onboarding dedicat", "Factură fiscală"],
          ctaLabel: "Contactează-ne",
          ctaType: "mailto",
          ctaHref: "mailto:hello@meetings.ro",
          highlight: false,
          badgeTone: "enterprise",
          testid: "pricing-enterprise-card",
        },
      ],
      addOn: {
        title: "Vertical dedicat",
        price: "90€",
        period: "/lună",
        detail: "Disponibil din Pro",
        verticals: ["Banking", "Healthcare", "Legal", "Jurnalism"],
      },
    },
    faq: {
      eyebrow: "Întrebări frecvente",
      title: "Răspunsuri simple pentru întrebările pe care le au instituțiile înainte să înceapă.",
      lead:
        "Am păstrat lucrurile simple: fără jargon, fără pași complicați, fără promisiuni greu de verificat.",
      items: [
        {
          question: "Trebuie să știu ceva tehnic ca să folosesc Meetings?",
          answer: "Nu. Încarci înregistrarea și primești raportul structurat. Dacă știi să folosești WhatsApp, te descurci și cu Meetings.",
          testid: "faq-item-technical",
        },
        {
          question: "Funcționează dacă nu am internet pe teren?",
          answer: "Da. Înregistrezi întâlnirea oriunde, apoi încarci fișierul când revii la birou. Acesta este avantajul fluxului offline upload.",
          testid: "faq-item-offline",
        },
        {
          question: "Pot exporta în Word și PDF?",
          answer: "Da. Raportul poate fi descărcat în PDF sau DOCX pentru tipărire, arhivare și trimitere internă.",
          testid: "faq-item-export",
        },
        {
          question: "Cum tratați confidențialitatea și GDPR?",
          answer: "Datele sunt procesate cu accent pe confidențialitate și flux dedicat pentru instituții. Evităm abordările nesigure pentru documente sensibile.",
          testid: "faq-item-gdpr",
        },
        {
          question: "Funcționează pentru domenii în afara administrației publice?",
          answer: "Da. Meetings.ro are verticale disponibile pentru Banking, Legal, Jurnalism și alte fluxuri dedicate, în funcție de plan.",
          testid: "faq-item-verticals",
        },
      ],
    },
    finalCta: {
      title: "Mai puține ore pierdute cu redactarea. Mai mult timp pentru decizie și implementare.",
      lead:
        "Descarcă Meetings.ro din stores imediat ce aplicația este publicată și păstrează aceeași experiență clară pentru ședințe, interviuri și rapoarte.",
      secondary: "Vezi prețurile",
    },
    footer: {
      statement:
        "Meetings.ro este secretarul digital creat pentru ședințe, interviuri și rapoarte structurate din România.",
      support: "Suport în limba română • Confidențialitate • Fluxuri pentru instituții publice",
      copyright: "© Meetings.ro",
    },
    preview: {
      title: "Raport generat",
      location: "Delta Dunării • Chilia Veche",
      generatedAt: "Generat în ~2 minute",
      summary: "Obiective, concluzii și pași următori apar structurat, gata pentru verificare internă.",
      tags: ["Data și ora", "Participanți", "Decizii", "Concluzii"],
      sections: ["Agenda", "Sinteză discuții", "Pași următori"],
    },
  },
  en: {
    locale: "en_US",
    meta: {
      title: "Meetings.ro — AI Recording & Transcription",
      description:
        "AI recording and transcription for meetings, interviews and structured reports. Built for Banking, Legal, Journalism and public administration.",
      keywords: [
        "AI recording",
        "AI transcription",
        "automated structured report",
        "public administration software",
        "meeting minutes",
        "banking compliance meeting reports",
        "legal transcription",
      ],
    },
    navigation: {
      features: "Features",
      structure: "9 fields",
      pricing: "Pricing",
      security: "Trust",
      faq: "FAQ",
      download: "Download",
      openMenu: "Open menu",
    },
    store: {
      tooltip: "Coming soon",
      label: "Download from stores",
      altAppStore: "Download Meetings.ro from the App Store",
      altPlayStore: "Download Meetings.ro from Google Play",
    },
    hero: {
      eyebrow: "AI transcription for teams and organizations",
      title: "Any meeting. Report in minutes.",
      lead:
        "AI transcription + structured reports for Banking, Legal, Journalism and public administration. Everything stays in a simple workflow that is easy to review.",
      secondaryCta: "See the sample report",
      trustLine: "If you can use WhatsApp, you can use Meetings.",
      proofs: [
        { value: "~2 min", label: "to generate an archive-ready report" },
        { value: "Offline", label: "record in the field and upload later" },
        { value: "RO", label: "Romanian-language support and onboarding" },
      ],
    },
    problem: {
      eyebrow: "Built for field reality",
      title: "We know the internet is not always on your side.",
      lead:
        "Meetings in the field, smaller localities or distributed organizations do not happen with perfect connectivity. Meetings is designed for that exact workflow.",
      body:
        "Record the meeting on any phone or recorder. Return to the office. Upload the file. Receive a structured report that is clear, concise and ready for internal review.",
      calloutTitle: "Offline upload",
      calloutBody:
        "Record anywhere, even with no signal. Upload the file once you are back at the office and continue processing without friction.",
      calloutBadge: "Works with weak connectivity",
      steps: [
        "1. Record the meeting on a phone, laptop or recorder.",
        "2. Upload the audio once internet is available again.",
        "3. Receive a structured document, not raw text.",
      ],
    },
    fields: {
      eyebrow: "Structured output, not simple transcription",
      title: "The 9 automatic fields that make every report audit-ready.",
      lead:
        "Meetings does not give you walls of text. It delivers information in the format your organization needs for review and archiving.",
      statement: "This is not just transcription. It is a clear, structured document built for official requirements.",
      items: [
        { label: "Date & time", description: "Locate the meeting instantly and preserve context." },
        { label: "Locality / UAT", description: "Archive correctly by commune, village or locality." },
        { label: "Attendees", description: "Keep the relevant participants visible in every report." },
        { label: "Agenda", description: "See discussion topics in the right order." },
        { label: "Objectives", description: "Separate the meeting purpose from the surrounding talk." },
        { label: "Discussion summary", description: "Capture what matters without re-reading raw transcription." },
        { label: "Decisions", description: "Extract the decisions without replaying the recording." },
        { label: "Conclusions", description: "Close the meeting with a concise summary." },
        { label: "Next steps", description: "Keep responsibilities and follow-up actions visible." },
      ],
    },
    verticals: {
      eyebrow: "Built for your industry",
      title: "The same workflow, adapted for the industries that need structure most.",
      lead:
        "Meetings.ro extracts the right information based on context without making the product harder to use.",
      cards: [
        {
          title: "GAL / Administrative",
          isNew: false,
          extracts: ["The 9 official fields", "Locality", "Attendees"],
          useCase: "LEADER reports generated automatically",
          testid: "industry-admin-card",
        },
        {
          title: "Banking & Finance",
          isNew: true,
          extracts: ["Compliance points", "Action items", "Risk flags"],
          useCase: "Meeting minutes aligned with BNR expectations",
          testid: "industry-banking-card",
        },
        {
          title: "Legal",
          isNew: true,
          extracts: ["Clauses discussed", "Deadlines", "Obligations"],
          useCase: "Structured negotiation documents instantly",
          testid: "industry-legal-card",
        },
        {
          title: "Journalism & Media",
          isNew: true,
          extracts: ["Key quotes", "Quoted people", "Editorial angle"],
          useCase: "Interviews transcribed and indexed",
          testid: "industry-media-card",
        },
      ],
      newBadge: "New",
    },
    features: {
      eyebrow: "Features for real administrative work",
      title: "Everything you need to find, export and recover any meeting quickly.",
      lead:
        "Beyond the generated report, Meetings helps teams stay organized and efficient when they need to revisit files months or years later.",
      cards: [
        {
          title: "Archive by locality",
          description: "Folders are auto-organized by localities such as Chilia Veche, Crișan or Maliuc.",
          detail: "Less time lost searching through old documents.",
          testid: "feature-archive-card",
        },
        {
          title: "Instant export",
          description: "Download the report as PDF or Word (DOCX) for printing and archiving.",
          detail: "No manual rewriting before sending it further.",
          testid: "feature-export-card",
        },
        {
          title: "Fast search",
          description: "Find any meeting by date or locality in seconds.",
          detail: "Useful when you revisit documents from previous years.",
          testid: "feature-search-card",
        },
      ],
    },
    security: {
      eyebrow: "Trust and confidentiality",
      title: "Data handled with the seriousness public administration expects.",
      lead:
        "For institutions, speed only matters if it comes together with confidentiality, clarity and local support.",
      bullets: [
        "GDPR-focused processing flow",
        "No unsafe public-cloud handling for sensitive documents",
        "Romanian-language technical support",
        "Built for local administrative workflows",
      ],
      badges: ["GDPR focused", "Romanian support", "Public sector fit"],
      cardTitle: "Made in Romania for Romanian institutions",
      cardLead:
        "We understand local terminology, pacing and bureaucracy. That is why the product prioritizes clarity, speed and proper archiving.",
      cardItems: [
        "Institution-focused processing",
        "Simple interface for non-technical users",
        "Reports that are easy to review and export",
      ],
    },
    pricing: {
      eyebrow: "New pricing in EUR",
      title: "Choose the plan that matches the real pace of your team.",
      lead:
        "We replaced the old pricing completely with EUR plans, clearer hour limits and industry access by tier.",
      toggleMonthly: "Monthly",
      toggleAnnual: "Annual",
      savingsLabel: "Save 2 months with annual billing",
      vatNote: "Prices exclude VAT",
      plans: [
        {
          name: "Free",
          badge: "Start",
          monthlyPrice: "0€",
          annualPrice: "0€",
          monthlyPeriod: "/month",
          annualPeriod: "/year",
          detail: "10h recording / month",
          features: ["AI model: Nano", "1 included vertical", "Basic PDF export", "1GB storage"],
          ctaLabel: "Coming soon",
          ctaType: "coming-soon",
          highlight: false,
          badgeTone: "neutral",
          testid: "pricing-free-card",
        },
        {
          name: "Pro",
          badge: "Upgrade",
          monthlyPrice: "20€",
          annualPrice: "200€",
          monthlyPeriod: "/month",
          annualPeriod: "/year",
          detail: "30h recording / month",
          features: ["AI model: Mini", "1 included vertical", "PDF + DOCX export", "10GB storage"],
          ctaLabel: "Coming soon",
          ctaType: "coming-soon",
          highlight: false,
          badgeTone: "neutral",
          testid: "pricing-pro-card",
        },
        {
          name: "Business",
          badge: "Popular",
          monthlyPrice: "60€",
          annualPrice: "600€",
          monthlyPeriod: "/month",
          annualPeriod: "/year",
          detail: "60h recording / month",
          features: ["AI model: Pro", "3 included verticals", "Branded PDF + DOCX export", "50GB storage", "Semantic search"],
          ctaLabel: "Choose Business",
          ctaType: "store-badges",
          highlight: true,
          badgeTone: "featured",
          testid: "pricing-business-card",
        },
        {
          name: "Enterprise",
          badge: "Enterprise",
          monthlyPrice: "900€",
          annualPrice: "900€",
          monthlyPeriod: "/year",
          annualPeriod: "/year",
          detail: "Unlimited hours",
          features: ["AI model: Pro", "Unlimited verticals", "99.9% SLA", "Dedicated onboarding", "Tax invoice"],
          ctaLabel: "Contact us",
          ctaType: "mailto",
          ctaHref: "mailto:hello@meetings.ro",
          highlight: false,
          badgeTone: "enterprise",
          testid: "pricing-enterprise-card",
        },
      ],
      addOn: {
        title: "Dedicated vertical",
        price: "90€",
        period: "/month",
        detail: "Available from Pro",
        verticals: ["Banking", "Healthcare", "Legal", "Journalism"],
      },
    },
    faq: {
      eyebrow: "Frequently asked questions",
      title: "Straight answers for the questions institutions ask before getting started.",
      lead:
        "We keep it simple: no jargon, no complex rollout, no promises that are hard to verify.",
      items: [
        {
          question: "Do I need technical skills to use Meetings?",
          answer: "No. Upload the recording and receive a structured report. If you can use WhatsApp, you can use Meetings.",
          testid: "faq-item-technical",
        },
        {
          question: "Does it work when there is no internet in the field?",
          answer: "Yes. Record the meeting anywhere, then upload the file once you are back at the office. That is the benefit of the offline upload workflow.",
          testid: "faq-item-offline",
        },
        {
          question: "Can I export to Word and PDF?",
          answer: "Yes. Reports can be downloaded as PDF or DOCX for printing, archiving and internal circulation.",
          testid: "faq-item-export",
        },
        {
          question: "How do you handle confidentiality and GDPR?",
          answer: "Data is processed with institutional confidentiality in mind and we avoid unsafe approaches for sensitive documents.",
          testid: "faq-item-gdpr",
        },
        {
          question: "Does it work for industries outside public administration?",
          answer: "Yes. Meetings.ro already supports dedicated verticals for Banking, Legal, Journalism and more depending on the chosen plan.",
          testid: "faq-item-verticals",
        },
      ],
    },
    finalCta: {
      title: "Less time lost on drafting. More time for decisions and follow-through.",
      lead:
        "Download Meetings.ro from the stores as soon as it goes live and keep the same clear workflow for meetings, interviews and structured reports.",
      secondary: "See pricing",
    },
    footer: {
      statement:
        "Meetings.ro is the digital secretary built for meetings, interviews and structured reports in Romania.",
      support: "Romanian-language support • Confidential processing • Built for public institutions",
      copyright: "© Meetings.ro",
    },
    preview: {
      title: "Generated report",
      location: "Danube Delta • Chilia Veche",
      generatedAt: "Generated in ~2 minutes",
      summary: "Objectives, conclusions and next steps appear in a structured format that is ready for internal review.",
      tags: ["Date & time", "Attendees", "Decisions", "Conclusions"],
      sections: ["Agenda", "Discussion summary", "Next steps"],
    },
  },
};
